// Generated by CoffeeScript 1.10.0
(function() {
  var Kijiji, window;

  Kijiji = module.exports;

  Kijiji.Date = require('d3').time.format("%d-%b-%y");

  Kijiji.attributes = {
    "expired": ".expired-ad-container",
    "title": "[itemprop=name]",
    "description": "[itemprop=description]",
    "price": "[itemprop=price]",
    "photographs": ["ul.photo-navigation img@src"],
    "publication date": "table.ad-attributes tr:first-child td"
  };

  window = require('x-ray')();

  window.concurrency(1);

  window.throttle(1, 333);

  Kijiji.read = function(address, done) {
    var id;
    id = Kijiji.parseIdentifierFromAddress(address);
    address = Kijiji.address(id);
    console.info({
      read: address
    });
    return window(address + "&siteLocale=en_CA", Kijiji.attributes)(function(error, output) {
      var ref;
      console.info({
        window: arguments
      });
      output["address"] = address;
      output["access time"] = Date.now();
      if (output["expired"] != null) {
        output["expired"] = Date.now();
        delete output["photographs"];
      } else {
        output["publication date"] = Kijiji.Date.parse(output["publication date"]);
        output["description"] = (ref = output["description"]) != null ? ref.trim() : void 0;
        output["photographs"] = output["photographs"].filter(function(p) {
          var ref1;
          return (p.match("play-button") === (ref1 = p.match("youtube")) && ref1 === null);
        });
      }
      return done(error, output);
    });
  };

  Kijiji.address = function(id) {
    return "http://www.kijiji.ca/v-view-details.html?adId=" + id;
  };

  Kijiji.parseIdentifierFromAddress = function(address) {
    var id, ref;
    console.info({
      parseIdentifierFromAddress: address
    });
    if (id = (ref = address.match(/adId=([0-9]+)/)) != null ? ref[1] : void 0) {
      return Number(id);
    } else {
      return Number(address.split("?")[0].split("/").pop());
    }
  };

}).call(this);
